"RMODE FILE for NEW PARSER"

<INSERT-FILE "P:BASEDEFS.MUD">
<INSERT-FILE "P:FIND">
<INSERT-FILE "P:TOP">
<INSERT-FILE "P:GRAM">
<INSERT-FILE "P:LALR.MUD">
<INSERT-FILE "P:LALRDEFS.MUD">
<INSERT-FILE "P:PARSER">
<INSERT-FILE "P:PBITDEFS.MUD">
;<INSERT-FILE "P:PMISC">
<INSERT-FILE "P:PDEFS">
<INSERT-FILE "P:PMEM">
<INSERT-FILE "P:PSTACK">
<INSERT-FILE "P:REDS">
<INSERT-FILE "P:BREDS">
<INSERT-FILE "P:SET.MUD">
<INSERT-FILE "P:SYMBOLS.MUD">
