"List of files for Challenge parser"

<COMPILATION-FLAG P-ARTHUR T>
<COMPILATION-FLAG P-PS-THEWORD <>>	;"Needed in REDS"

<COMPILATION-FLAG P-DEBUGGING-PARSER <>>
<COMPILATION-FLAG P-BE-VERB T>
<COMPILATION-FLAG SELECTIVE-HINTS T>
;<COMPILATION-FLAG SPLIT-HINTS T>

<INSERT-FILE "CONSTANTS">
<INSERT-FILE "PSTACK">
<INSERT-FILE "PMEM">
<INSERT-FILE "PDEFS">
<INSERT-FILE ;"<CHALLENGE>" "DEFS2">
<INSERT-FILE "PARSER">
<INSERT-FILE "FIND">
<INSERT-FILE "REDS">
<INSERT-FILE "BREDS">
<INSERT-FILE "GRAM">
<INSERT-FILE "TOP">
<INSERT-FILE "PRARE">
